import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import Navbar from "./components/navbar/Navbar";
import ResumoCarrinho from "./components/ResumoCarrinho/ResumoCarrinho";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en">
        
        <body>
            <Navbar/>
            <main>
              <div className="container p-5">
                {children}
              </div>
            </main>
        </body>
      </html>

  );
}
